config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Sigtap::Application.routes.draw do

  namespace :admin do
    resources :area_protegidas, path: "areas_protegidas" do

      member do
        get :downloadable
      end

      resources :informacion_legals, path: "informacion_legal"
      resources :informacion_administrativas, path: "informacion_administrativa"
      resources :informacion_geograficas, path: "informacion_geografica"
      resources :categorizacions, path: "categorizaciones"
      resources :informacion_climaticas, path: "informacion_climatica"
      resources :informacion_turisticas, path: "informacion_turistica"
      resources :amenazas, path: "amenaza"
      resources :biodiversidads, path: "biodiversidad" do
        resources :biodiversidad_especies
      end
      resources :informacion_hidrograficas, path: "informaciones_hidrograficas"
      resources :deforestacions, path: "deforestaciones"
      resources :extraccion_ilegals, path: "extracciones_ilegales"
      resources :amenaza_especies
      resources :incendios
      resources :actividad_agropecuaria, path: "actividad_agropecuaria"
      resources :mineria_ilegals, path: "mineria_ilegal"
      resources :mineria_legals, path: "mineria_legales"
      resources :infraestructura_vials, path: "infraestructuras_viales"
      resources :otra_infraestructuras, path: "otras_infraestructuras"
      resources :especie_introducidas, path: "especies_introducidas"
      resources :comunidads, path: "comunidades"
      resources :actividad_hidrocarburiferas, path: "actividades_hidrocarburiferas"
      resources :conflicto_socioambientals, path: "conflictos_socioambientales"
      resources :invasions, path: "invasiones"
      resources :sitio_turisticos, path: "sitios_turisticos"
    end
  end

  resources :areas_protegidas do
    collection do
      get :maps
      get 'show/:id' => 'areas_protegidas#show'
    end
  end
  resources :sessions, path: :login
  get 'login' => 'sessions#index', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  root :to => 'areas_protegidas#maps'

  mount Sidekiq::Web, at: '/sidekiq_web', :constraints => AdminConstraint.new

  match '*a', :to => 'application#routing_error'
end

app/models/extraccion_ilegal.rb
class ExtraccionIlegal < ActiveRecord::Base
  attr_accessible :AMENAZA_ID,
                  :EXT_ILE_CANTIDAD,
                  :EXT_ILE_MAT_TIPO,
                  :EXT_ILE_TIPO,
                  :EXT_ILE_USOS,
                  :amenazas_especies_attributes

  self.table_name = "EXTRACCION_ILEGAL"
  self.primary_key = :EXT_ILE_ID

  belongs_to :amenaza, foreign_key: :AMENAZA_ID

  has_many :amenazas_especies, class_name: "AmenazaEspecie",
                            foreign_key: :EXT_ILE_ID,
                            dependent: :destroy
  accepts_nested_attributes_for :amenazas_especies, :reject_if => lambda { |a| a[:AME_ESP_NOMBRE_CIENTIFICO].blank? }, :allow_destroy => true

  def AREA_ID
    self.area_protegida.AREA_ID
  end

  # validates :EXT_ILE_TIPO, :presence => true
  # validates :EXT_ILE_MAT_TIPO, :presence => true
  # validates :EXT_ILE_USOS, :presence => true
  # validates :EXT_ILE_CANTIDAD, :presence => true
  validates :EXT_ILE_CANTIDAD, :numericality => {:greater_than => 0}, :allow_blank => true


end

app/controllers/admin/extraccion_ilegals_controller.rb
# encoding: utf-8
class Admin::ExtraccionIlegalsController < AdminController
  before_filter :find_area_protegida, :set_div_for_js
  # GET /extraccion_ilegals
  # GET /extraccion_ilegals.json
  
  def index
    @amenazas = @area_protegida.amenazas_extracciones_ilegales.all
  end

  # GET /extraccion_ilegals/1
  # GET /extraccion_ilegals/1.json
  def show
    redirect_to action: :index
    # @extraccion_ilegal = ExtraccionIlegal.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @extraccion_ilegal }
    # end
  end

  # GET /extraccion_ilegals/new
  # GET /extraccion_ilegals/new.json
  def new
    # @amenaza = @area_protegida.amenazas.build
    # @extraccion_ilegal = @amenaza.extracciones_ilegales.build

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @extraccion_ilegal }
    # end
    @amenaza = @area_protegida.amenazas.new(:AMENAZA_TIPO => "Extracción Ilegal")
    @amenaza.extracciones_ilegales.build

    render 'admin/amenazas/new'
  end

  # GET /extraccion_ilegals/1/edit
  def edit
    # @extraccion_ilegal = ExtraccionIlegal.find(params[:id])
    @amenaza = @area_protegida.amenazas.find params[:id]
    render 'admin/amenazas/new'
  end

  # POST /extraccion_ilegals
  # POST /extraccion_ilegals.json
  def create
    redirect_to action: :index
    # amenaza_attrs = params[:extraccion_ilegal].delete :amenaza
    # @amenaza = @area_protegida.amenazas.create(amenaza_attrs)    
    # @extraccion_ilegal = @amenaza.extracciones_ilegales.build(params[:extraccion_ilegal])



    # respond_to do |format|
    #   if @extraccion_ilegal.save
    #     format.html { redirect_to admin_area_protegida_amenaza_path(@area_protegida, @amenaza), notice: 'Amenaza creada'}
    #     format.json { render json: @extraccion_ilegal, status: :created, location: @extraccion_ilegal }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @extraccion_ilegal.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /extraccion_ilegals/1
  # PUT /extraccion_ilegals/1.json
  def update
    redirect_to action: :index
    # @extraccion_ilegal = ExtraccionIlegal.find(params[:id])

    # respond_to do |format|
    #   if @extraccion_ilegal.update_attributes(params[:extraccion_ilegal])
    #     format.html { redirect_to @extraccion_ilegal, notice: 'Extraccion ilegal was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: "edit" }
    #     format.json { render json: @extraccion_ilegal.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /extraccion_ilegals/1
  # DELETE /extraccion_ilegals/1.json
  def destroy
    @extraccion_ilegal = ExtraccionIlegal.find(params[:id])
    @extraccion_ilegal.destroy

    respond_to do |format|
      format.html { redirect_to admin_area_protegida_extraccion_ilegals_path(@area_protegida) }
      format.json { head :no_content }
      format.js {
        index
        render :index
      }
    end
  end

  private

    def set_div_for_js
      @div_name = "#extracción_ilegal"
    end
end

app/helpers/extraccion_ilegals_helper.rb
module ExtraccionIlegalsHelper
end

app/views/admin/extraccion_ilegals/_extraccion_ilegal.html.erb
  <div class="info_title">Tipo de especies:</div>
  <div class="info_content">
    <%= extraccion_ilegal.EXT_ILE_TIPO %> 
  </div>
  <div class="info_content">
      <% extraccion_ilegal.amenazas_especies.each do |amenaza_especie| %>
          <%= render 'admin/amenaza_especies/amenaza_especie', amenaza_especie: amenaza_especie %>
      <% end %>
    </div>
  <div class="info_title">Tipo de material:</div>
  <div class="info_content">
    <%= extraccion_ilegal.EXT_ILE_MAT_TIPO %> 
  </div>
  <div class="info_title">Usos</div>
  <div class="info_content">
    <%= extraccion_ilegal.EXT_ILE_USOS %> 
  </div>
  <div class="info_title">Cantidad de material:</div>
  <div class="info_content">
    <%= extraccion_ilegal.EXT_ILE_CANTIDAD %> 
  </div>
  <% unless extraccion_ilegal.amenazas_especies.count == 0 %>
    <div class="info_title">
      Especies
    </div>
    
  <% end %>

  <% if current_user and current_user.is_admin? %>
    <div>
      <%= link_to 'Editar', edit_admin_area_protegida_extraccion_ilegal_path(@area_protegida, extraccion_ilegal.amenaza), :class => "editar_edit", :remote => true %>
      <%= link_to 'Eliminar', admin_area_protegida_extraccion_ilegal_path(@area_protegida, extraccion_ilegal), method: :delete, data: { confirm: '¿Estás seguro? Esta acción es irreversible' }, :class => "delete_destroy", :remote => true %>
    </div>
  <% end %>

app/views/admin/extraccion_ilegals/_form.html.erb
  <div class="field">
    <%= f.label :EXT_ILE_TIPO, "Tipo de especies" %>
    <%= f.select :EXT_ILE_TIPO,["Flora", "Fauna"]%> 
  </div>


  <div class="field">
    <div class="info_title">Especies</div>
    <div class="info_content">
      <%= f.fields_for :amenazas_especies do |b| %>
        <%= render 'admin/amenaza_especies/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Especie", :amenazas_especies, :class => "crear_nuevo" %>
    </div>
  </div>

    <div class="field">
    <%= f.label :EXT_ILE_MAT_TIPO, "Tipo de Material" %>
    <%= f.select :EXT_ILE_MAT_TIPO,["Individuos", "Semillas","Plantulas","Partes"]%> 
  </div>
  <div class="field">
    <%= f.label :EXT_ILE_USOS, "Usos" %>
    <%= f.text_field :EXT_ILE_USOS %>
      <span class="help-inline">No puede quedar en blanco</span> 
  </div>
  <div class="field">
    <%= f.label :EXT_ILE_CANTIDAD, "Cantidad de material" %>
    <%= f.number_field :EXT_ILE_CANTIDAD%>
      <span class="help-inline">
        Por favor verifica que hayas ingresado un número y que sea mayor a 0.
      </span> 
    <%= f.link_to_remove "Extracción ilegal", :class => "delete_destroy" %>
  </div>

app/views/admin/extraccion_ilegals/_index.html.erb
<% amenazas.each do |amenaza| %>
  <div class="has_container has_margin">
	  <%= render 'admin/amenazas/amenaza', amenaza: amenaza %>
  	<div></div>
  		<% amenaza.extracciones_ilegales.each do |extraccion_ilegal| %>
    		<div class="info_content">
      		<%= render 'admin/extraccion_ilegals/extraccion_ilegal', extraccion_ilegal: extraccion_ilegal%>
    		</div>
  		<% end %>
  	</div>
<% end %>

<% if current_user and current_user.is_admin? %>
  <div class="">
    <%= link_to 'Añadir extracción ilegal', new_admin_area_protegida_extraccion_ilegal_path(@area_protegida), :class => "crear_nuevo", :remote => true %> 
  </div>
<% end %>

app/views/admin/extraccion_ilegals/index.html.erb
<%= javascript_tag do %>
  window.location = '/admin/areas_protegidas';
<% end -%>

<h2><%= @area_protegida.AREA_NOMBRE %></h2>
<h3>Extracción ilegal</h3>


<%= render 'index', amenazas: @amenazas%>

<br>
<%= link_to "Atrás", admin_area_protegida_path(@area_protegida), :class => "atras_back" %>
<%= link_to 'Añadir Amenaza: Extracción Ilegal', new_admin_area_protegida_extraccion_ilegal_path(@area_protegida), :remote => true, :class => "crear_nuevo" %>

app/views/admin/extraccion_ilegals/index.js.erb
<%= js_content "#extracción_ilegal", j(render('index', amenazas: @amenazas)) %>

app/views/admin/extraccion_ilegals/show.html.erb
<%= render 'extraccion_ilegal', deforestacion: @extraccion_ilegal %>