config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Sigtap::Application.routes.draw do

  namespace :admin do
    resources :area_protegidas, path: "areas_protegidas" do

      member do
        get :downloadable
      end

      resources :informacion_legals, path: "informacion_legal"
      resources :informacion_administrativas, path: "informacion_administrativa"
      resources :informacion_geograficas, path: "informacion_geografica"
      resources :categorizacions, path: "categorizaciones"
      resources :informacion_climaticas, path: "informacion_climatica"
      resources :informacion_turisticas, path: "informacion_turistica"
      resources :amenazas, path: "amenaza"
      resources :biodiversidads, path: "biodiversidad" do
        resources :biodiversidad_especies
      end
      resources :informacion_hidrograficas, path: "informaciones_hidrograficas"
      resources :deforestacions, path: "deforestaciones"
      resources :extraccion_ilegals, path: "extracciones_ilegales"
      resources :amenaza_especies
      resources :incendios
      resources :actividad_agropecuaria, path: "actividad_agropecuaria"
      resources :mineria_ilegals, path: "mineria_ilegal"
      resources :mineria_legals, path: "mineria_legales"
      resources :infraestructura_vials, path: "infraestructuras_viales"
      resources :otra_infraestructuras, path: "otras_infraestructuras"
      resources :especie_introducidas, path: "especies_introducidas"
      resources :comunidads, path: "comunidades"
      resources :actividad_hidrocarburiferas, path: "actividades_hidrocarburiferas"
      resources :conflicto_socioambientals, path: "conflictos_socioambientales"
      resources :invasions, path: "invasiones"
      resources :sitio_turisticos, path: "sitios_turisticos"
    end
  end

  resources :areas_protegidas do
    collection do
      get :maps
      get 'show/:id' => 'areas_protegidas#show'
    end
  end
  resources :sessions, path: :login
  get 'login' => 'sessions#index', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  root :to => 'areas_protegidas#maps'

  mount Sidekiq::Web, at: '/sidekiq_web', :constraints => AdminConstraint.new

  match '*a', :to => 'application#routing_error'
end

app/controllers/admin/amenazas_controller.rb
# encoding: utf-8
class Admin::AmenazasController < AdminController

  before_filter :find_area_protegida, :confirm_logged_in
  
  # GET /amenazas
  # GET /amenazas.json
  def index
    redirect_to admin_area_protegida_path(@area_protegida)
    # @amenazas = @area_protegida.amenazas.all

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @amenazas }
    # end
  end

  # GET /amenazas/1
  # GET /amenazas/1.json
  def show
    redirect_to admin_area_protegida_path(@area_protegida)
    # @amenaza = @area_protegida.amenazas.find params[:id]


    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @amenaza }
    # end
  end

  # GET /amenazas/new
  # GET /amenazas/new.json
  def new
    redirect_to admin_area_protegida_path(@area_protegida)
    # @amenaza = @area_protegida.amenazas.build


    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @amenaza }
    # end
  end

  # GET /amenazas/1/edit
  def edit
    redirect_to admin_area_protegida_path(@area_protegida)
    # @amenaza = @area_protegida.amenazas.find(params[:id])
  end

  # POST /amenazas
  # POST /amenazas.json
  def create
    # redirect_to admin_area_protegida_path(@area_protegida)
    @amenaza = @area_protegida.amenazas.new(params[:amenaza])

    respond_to do |format|
      if @amenaza.save
        format.js { 
          case @amenaza.AMENAZA_TIPO
          when "Deforestación"
            redirect_to admin_area_protegida_deforestacions_path(@area_protegida)
          when "Extracción Ilegal"
            redirect_to admin_area_protegida_extraccion_ilegals_path(@area_protegida)
          when "Incendio"
            redirect_to admin_area_protegida_incendios_path(@area_protegida)
          when "Actividad Agropecuaria"
            redirect_to admin_area_protegida_actividad_agropecuaria_path(@area_protegida)
          when "Minería Ilegal"
            redirect_to admin_area_protegida_mineria_ilegals_path(@area_protegida)
            flash["notice"] = "Minería Ilegal creada."
          when "Minería Legal en el límite del Área Protegida"
            redirect_to admin_area_protegida_mineria_legals_path(@area_protegida)
          when "Infraestructura Vial"
            redirect_to admin_area_protegida_infraestructura_vials_path(@area_protegida)
            flash["notice"] = "Infraestructura vial creada."
          when "Obras de infraestructura"
            redirect_to admin_area_protegida_otra_infraestructuras_path(@area_protegida)
            flash["notice"] = "Otra infraestructura creada."
          when "Especies introducidas"
            redirect_to admin_area_protegida_especie_introducidas_path(@area_protegida)
            flash["notice"] = "Especie introducida creada."
          when "Actividades Hidrocarburíferas"
            redirect_to admin_area_protegida_actividad_hidrocarburiferas_path(@area_protegida)
            flash["notice"] = "Actividad hidrocarburífera creada."
          when "Invasiones"
            redirect_to admin_area_protegida_invasions_path(@area_protegida)
            flash["notice"] = "Invasión creada."
          end
        }
        format.json { render json: @amenaza, status: :created, location: @amenaza }
      else
        # format.html { render action: "new" }
        #format.json { render json: @amenaza.errors, status: :unprocessable_entity }
        
        format.js {
          case @amenaza.AMENAZA_TIPO
          when "Minería Legal en el límite del Área Protegida"
            @div_name = "#minería_legal_en_el_límite_del_Área_protegida"
            render :new
          when "Deforestación"
            @div_name = "#deforestación"
            render :new
          when "Extracción Ilegal"
            @div_name = "#extracción_ilegal"
            render :new
          when "Incendio"
            @div_name = "#incendios"
            render :new
          when "Actividad Agropecuaria"
            @div_name = "#actividad_agropecuaria"
            render :new
          when "Minería Ilegal"
            @div_name = "#minería_ilegal"
            render :new
          when "Infraestructura Vial"
            @div_name = "#infraestructura_vial"
            render :new
          when "Obras de infraestructura"
            @div_name = "#obras_de_infraestructura"
            render :new
          when "Especies introducidas"
            @div_name = "#especies_introducidas"
            render :new
          when "Actividades Hidrocarburíferas"
            @div_name = "#actividades_hidrocarburíferas"
            render :new
          when "Invasiones"
            @div_name = "#invasiones"
            render :new
          end
        }
        
      end
    end
  end

  # PUT /amenazas/1
  # PUT /amenazas/1.json
  def update
    # redirect_to admin_area_protegida_path(@area_protegida)
    @amenaza = @area_protegida.amenazas.find(params[:id])


    respond_to do |format|
      if @amenaza.update_attributes(params[:amenaza])
        format.js {
          case @amenaza.AMENAZA_TIPO
          when "Deforestación"
            redirect_to admin_area_protegida_deforestacions_path(@area_protegida)
          when "Extracción Ilegal"
            redirect_to admin_area_protegida_extraccion_ilegals_path(@area_protegida)
            flash["notice"] = 'Extracción ilegal actualizada.'
          when "Incendio"
            redirect_to admin_area_protegida_incendios_path(@area_protegida)
            flash["notice"] = 'Incendio actualizada.'
          when "Actividad Agropecuaria"
            redirect_to admin_area_protegida_actividad_agropecuaria_path(@area_protegida)
            flash["notice"] = "Actividad Agropecuaria actualizada."
          when "Minería Ilegal"
            redirect_to admin_area_protegida_mineria_ilegals_path(@area_protegida)
            flash["notice"] = "Minería Ilegal actualizada."
          when "Infraestructura Vial"
            redirect_to admin_area_protegida_infraestructura_vials_path(@area_protegida)
            flash["notice"] = "Infraestructura vial actualizada."
          when "Obras de infraestructura"
            redirect_to admin_area_protegida_otra_infraestructuras_path(@area_protegida)
            flash["notice"] = "Otra infraestructura actualizada."
          when "Minería Legal en el límite del Área Protegida"
            redirect_to admin_area_protegida_mineria_legals_path(@area_protegida)
            flash["notice"] = "Minería legal actualizada."
          when "Especies introducidas"
            redirect_to admin_area_protegida_especie_introducidas_path(@area_protegida)
            flash["notice"] = "Especie introducida actualizada."
          when "Actividades Hidrocarburíferas"
            redirect_to admin_area_protegida_actividad_hidrocarburiferas_path(@area_protegida)
            flash["notice"] = "Actividad hidrocarburífera actualizada."
          when "Invasiones"
            redirect_to admin_area_protegida_invasions_path(@area_protegida)
            flash["notice"] = "Invasión actualizada."
          end
        }
        format.json { head :no_content }
      else
        
        format.js {
          case @amenaza.AMENAZA_TIPO
          when "Minería Legal en el límite del Área Protegida"
            @div_name = "#minería_legal_en_el_límite_del_Área_protegida"
            render :new
          when "Deforestación"
            @div_name = "#deforestación"
            render :new
          when "Extracción Ilegal"
            @div_name = "#extracción_ilegal"
            render :new
          when "Incendio"
            @div_name = "#incendios"
            render :new
          when "Actividad Agropecuaria"
            @div_name = "#actividad_agropecuaria"
            render :new
          when "Minería Ilegal"
            @div_name = "#minería_ilegal"
            render :new
          when "Infraestructura Vial"
            @div_name = "#infraestructura_vial"
            render :new
          when "Obras de infraestructura"
            @div_name = "#obras_de_infraestructura"
            render :new
          when "Especies introducidas"
            @div_name = "#especies_introducidas"
            render :new
          when "Actividades Hidrocarburíferas"
            @div_name = "#actividades_hidrocarburíferas"
            render :new
          when "Invasiones"
            @div_name = "#invasiones"
            render :new
          end
        }
      end
    end
  end

  # DELETE /amenazas/1
  # DELETE /amenazas/1.json
  def destroy
    # redirect_to admin_area_protegida_path(@area_protegida)
    @amenaza = @area_protegida.amenazas.find(params[:id])
    @amenaza.destroy



    respond_to do |format|
      format.html { redirect_to admin_area_protegida_amenazas_url(@area_protegida) }
      format.json { head :no_content }
      format.js {
        case @amenaza.AMENAZA_TIPO
          when "Deforestación"
            redirect_to controller: :deforestacions, action: :index, status: 303
          when "Extracción Ilegal"
            redirect_to controller: :extraccion_ilegals, action: :index, status: 303
          when "Incendio"
            redirect_to controller: :incendios, action: :index, status: 303
          when "Actividad Agropecuaria"
            redirect_to controller: :actividad_agropecuaria, action: :index, status: 303
          when "Minería Ilegal"
            redirect_to controller: :mineria_ilegals, action: :index, status: 303
          when "Minería Legal en el límite del Área Protegida"
            redirect_to controller: :mineria_legals, action: :index, status: 303
          when "Infraestructura Vial"
            redirect_to controller: :infraestructura_vials, action: :index, status: 303
          when "Obras de infraestructura"
            redirect_to controller: :otra_infraestructuras, action: :index, status: 303
          when "Especies introducidas"
            redirect_to controller: :especie_introducidas, action: :index, status: 303

app/helpers/amenazas_helper.rb
module AmenazasHelper
end

app/views/admin/amenazas/_amenaza.html.erb
<div class="">

<div class="info_title">Levantada a la fecha:</div>
<div class="info_content">
  <%= l amenaza.AMENAZA_FECHA_LEVANTADA, format: :long %>
</div>

<div class="info_title">Fecha del evento:</div>
<div class="info_content">
  <%= l amenaza.AMENAZA_FECHA_EVENTO, format: :long %>
</div>

<% unless amenaza.responsable.blank? %>
<div class="info_title">Responsable del registro:</div>
<div class="info_content">
  <%=  amenaza.responsable %>
</div>
<%end%>

<div class="info_title">Ubicación Geográfica:</div>
<div class="info_content">
  <% unless amenaza.datum.blank? %>
    <div>
      <strong>Datum:</strong>
      <%= amenaza.datum %>
    </div>
  <%end%>
  <% unless amenaza.coordenada_norte.blank? %>
    <div>
      <strong>Coordenada utm norte:</strong>
      <%= amenaza.coordenada_norte %>
    </div>
  <%end%>
  <% unless amenaza.coordenada_este.blank? %>
    <div>
      <strong>Coordenada utm este:</strong>
      <%= amenaza.coordenada_este %>
    </div>
  <%end%>
  <% unless amenaza.altitud_minima.blank? %>
    <div>
      <strong>Altitud mínima:</strong>
      <%= amenaza.altitud_minima %>
    </div>
  <%end%>
  <% unless amenaza.altitud_maxima.blank? %>
    <div>
      <strong>Altitud máxima:</strong>
      <%= amenaza.altitud_maxima %>
    </div>
  <%end%>
  <div class="info_title">Jurisdicción:</div>
<div class="info_content">
  <p>
    <b>Provincia:</b>
    <%= amenaza.area_protegida.provincia or raw("<small>(No definido)</small>") %>
  </p>
  <p>
    <b>Cantón:</b>
    <%= amenaza.area_protegida.canton or raw("<small>(No definido)</small>") %>
  </p>
  <p>
    <b>Parroquia:</b>
    <%= amenaza.area_protegida.parroquia or raw("<small>(No definido)</small>") %>
  </p>
</div>
</div>

<% unless amenaza.AMENAZA_CONTRAVENTOR_TIPO.blank? %>
  <div class="info_title">Tipo de contraventor:</div>
  <div class="info_content">
    <%=  amenaza.AMENAZA_CONTRAVENTOR_TIPO %>
  </div>
<% end %>

<% if current_user and current_user.is_admin? %>
  <div>
    <%= link_to "Eliminar Amenaza", admin_area_protegida_amenaza_path(@area_protegida, amenaza), method: :delete, data: { confirm: '¿Estás seguro? Esta acción es irreversible' } , :class => "delete_destroy", :remote => true %>
  </div>
<% end %>

</div>

app/views/admin/amenazas/_form.html.erb
<%= nested_form_for([:admin, @area_protegida, @amenaza], :remote => true) do |f| %>
  
  <div class="field">
    <%= f.label :AREA_ID, "Área protegida" %>
    <input type="text" disabled="disabled" value="<%= @area_protegida.AREA_NOMBRE %>">
    <%= f.hidden_field :AREA_ID %>
  </div>

  <div class="field">
    <%= f.label :AMENAZA_FECHA_LEVANTADA, "Levantada la fecha" %>
    <%= f.text_field :AMENAZA_FECHA_LEVANTADA, {:start_year => 1995, :class => "datepicker"}%>
    <span class="help-inline">Comprueba que la fecha de levantamiento se haya especificado y que no sea mayor a la fecha actual.</span>
  </div>
  <div class="field">
    <%= f.label :AMENAZA_FECHA_EVENTO, "Fecha del evento" %>
    <%= f.text_field :AMENAZA_FECHA_EVENTO, {:start_year => 1995, :class => "datepicker"}%>
    <span class="help-inline">Comprueba que la fecha del evento se haya especificado y que no sea mayor a la fecha actual.</span> 
  </div>
    <div class="field">
    <%= f.label :responsable, "Responsable del registro" %>
    <%= f.text_field :responsable%>
      <span class="help-inline">No puede quedar en blanco</span> 
  </div>
  <div class="info_title">
    Ubicación
  </div>
  <div class="info_content">
    <div class="info_title">Ubicación Geográfica</div>
      <div class="info_content">
        <div class="field">
          <%= f.label :datum, "Datum" %>
          <%= f.text_field :datum %>
        </div>
      <div class="field">
        <%= f.label :coordenada_norte, "Coordenadas UTM Norte" %>
        <%= f.number_field :coordenada_norte, :step => "any" %>
        <span class="help-inline">Tiene que se un número mayor a 0</span> 
      </div>
      <div class="field">
        <%= f.label :coordenada_este, "Coordenadas UTM Este" %>
        <%= f.number_field :coordenada_este, :step => "any" %>
        <span class="help-inline">Tiene que se un número mayor a 0</span>
      </div>
      <div class="field">
        <%= f.label :altitud_minima, "Altitud mínima (m)" %>
        <%= f.number_field :altitud_minima, :step => "any" %>
        <span class="help-inline">Tiene que se un número mayor a 0</span>
      </div>
      <div class="field">
        <%= f.label :altitud_maxima, "Altitud máxima (m)" %>
        <%= f.number_field :altitud_maxima, :step => "any" %>
        <span class="help-inline">Tiene que se un número mayor a 0</span>
      </div>
  </div>

<div class="info_title">Jurisdicción</div>
<div class="info_content">
  <div class="field">
      <%= f.label :provincia, "Provincia" %>
      <input type="text" disabled="disabled" value="<%= @area_protegida.provincia %>" placeholder="Llenar de Información Geográfica del Área Protegida">
    </div>
    <div class="field">
      <%= f.label :canton, "Cantón" %>
      <input type="text" disabled="disabled" value="<%= @area_protegida.canton %>" placeholder="Llenar de Información Geográfica del Área Protegida">
    </div>
    <div class="field">
      <%= f.label :canton, "Parroquia" %>
      <input type="text" disabled="disabled" value="<%= @area_protegida.parroquia %>" placeholder="Llenar de Información Geográfica del Área Protegida">
    </div>
</div>

  </div>

    <div class="field">
    <%= f.label :AMENAZA_CONTRAVENTOR_TIPO, "Tipo de Contraventor" %>
    <%= f.select :AMENAZA_CONTRAVENTOR_TIPO,["Nativo", "Colonos","Intermediarios", "Extranjeros"]%>
  </div>
  <div class="field">
    <%= f.label :AMENAZA_TIPO, "Tipo de evento" %>
    <%= f.text_field :AMENAZA_TIPO, :disabled => true, :required => true %>
    <%= f.hidden_field :AMENAZA_TIPO %>
  </div>

  <% case f.object.AMENAZA_TIPO %>
  <% when "Deforestación" %>
    <!-- deforestaciones: -->
    <div class="info_title">
      Deforestación
    </div>
    <div class="info_content">
      <%= f.fields_for :deforestaciones do |b| %>
        <%= render 'admin/deforestacions/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Deforestación", :deforestaciones, :class => "crear_nuevo" %>
    </div>

  <% when "Extracción Ilegal" %>
    <!-- extracciones ilegales: -->
    <div class="info_title">
      Extracción Ilegal
    </div>
    <div class="info_content">
      <%= f.fields_for :extracciones_ilegales do |b| %>
        <%= render 'admin/extraccion_ilegals/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Extracción Ilegal", :extracciones_ilegales, :class => "crear_nuevo" %>
    </div>

  <% when "Incendio" %>
    <!-- incendios: -->
    <div class="info_title">
      Incendio
    </div>
    <div class="info_content">
      <%= f.fields_for :incendios do |b| %>
        <%= render 'admin/incendios/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Incendio", :incendios, :class => "crear_nuevo" %>
    </div>

  <% when "Actividad Agropecuaria" %>
    <!-- Actividad Agropecuaria: -->
    <div class="info_title">
      Actividad Agropecuaria
    </div>
    <div class="info_content">
      <%= f.fields_for :actividades_agropecuarias do |b| %>
        <%= render 'admin/actividad_agropecuaria/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Actividad Agropecuaria", :actividades_agropecuarias, :class => "crear_nuevo" %>
    </div>
  <% when "Minería Legal en el límite del Área Protegida" %>
    <!-- mineria legal: -->
    <div class="info_title">
      Minería Legal en el límite del Área Protegida
    </div>
    <div class="info_content">
      <%= f.fields_for :minerias_legales do |b| %>
        <%= render 'admin/mineria_legals/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Minería Legal", :minerias_legales, :class => "crear_nuevo" %>
    </div>

  <% when "Minería Ilegal" %>
    <!-- Minería Ilegal -->
    <div class="info_title">Minería Ilegal</div>
    <div class="info_content">
      <%= f.fields_for :minerias_ilegales do |b| %>
        <%= render 'admin/mineria_ilegals/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Minería Ilegal", :minerias_ilegales, :class => "crear_nuevo" %>
    </div>

<% when "Infraestructura Vial" %>
    <!-- Infraestructura Vial -->
    <div class="info_title">Infraestructura Vial</div>
    <div class="info_content">
      <%= f.fields_for :infraestructuras_viales do |b| %>
        <%= render 'admin/infraestructura_vials/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Infraestructura vial", :infraestructuras_viales, :class => "crear_nuevo" %>
    </div>

<% when "Obras de infraestructura" %>
    <!-- Otra infraestructura -->
    <div class="info_title">Obras de infraestructura</div>
    <div class="info_content">
      <%= f.fields_for :otras_infraestructuras do |b| %>
        <%= render 'admin/otra_infraestructuras/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Obras de infraestructura", :otras_infraestructuras, :class => "crear_nuevo" %>
    </div>

<% when "Especies introducidas" %>
    <!-- Especies introducidas -->
    <div class="info_title">Especies introducidas</div>
    <div class="info_content">
      <%= f.fields_for :especies_introducidas do |b| %>
        <%= render 'admin/especie_introducidas/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Especies introducidas", :especies_introducidas, :class => "crear_nuevo" %>
    </div>

<% when "Actividades Hidrocarburíferas" %>
    <!-- Actividades Hidrocarburíferas -->
    <div class="info_title">Actividades hidrocarburíferas</div>
    <div class="info_content">
      <%= f.fields_for :actividades_hidrocarburiferas do |b| %>
        <%= render 'admin/actividad_hidrocarburiferas/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Actividad hidrocarburífera", :actividades_hidrocarburiferas, :class => "crear_nuevo" %>
    </div>

<% when "Invasiones" %>
    <!-- Invasiones -->
    <div class="info_title">Invasiones</div>
    <div class="info_content">
      <%= f.fields_for :invasiones do |b| %>
        <%= render 'admin/invasions/form', f: b %>
      <% end -%>
      <%= f.link_to_add "Invasión", :invasiones, :class => "crear_nuevo" %>
    </div>

  <% end %>

  <div class="actions">
    <%= f.submit :disable_with => "Enviando.." %>
  </div>
<% end %>

<% case @amenaza.AMENAZA_TIPO %>
<% when "Deforestación" %>
  <%= link_to 'Cancelar', admin_area_protegida_deforestacions_path(@area_protegida),:class => "cancel_button", :remote => true %>
<% when "Extracción Ilegal" %>
  <%= link_to 'Cancelar', admin_area_protegida_extraccion_ilegals_path(@area_protegida), :class => "cancel_button", :remote => true %>
<% when "Incendio" %>
  <%= link_to 'Cancelar', admin_area_protegida_incendios_path(@area_protegida), :class => "cancel_button", :remote => true %>
<% when "Actividad Agropecuaria" %>
  <%= link_to 'Cancelar', admin_area_protegida_actividad_agropecuaria_path(@area_protegida), :class => "cancel_button", :remote => true %> 
<% when "Minería Ilegal" %>
  <%= link_to "Cancelar", admin_area_protegida_mineria_ilegals_path(@area_protegida), :remote => true, :class => "cancel_button" %>
<% when "Minería Legal en el límite del Área Protegida" %>
  <%= link_to 'Cancelar', admin_area_protegida_mineria_legals_path(@area_protegida), :remote => true, :class => "cancel_button" %>
<% when "Infraestructura Vial" %>
  <%= link_to 'Cancelar', admin_area_protegida_infraestructura_vials_path(@area_protegida), :remote => true, :class => "cancel_button" %>
<% when "Obras de infraestructura" %>
  <%= link_to 'Cancelar', admin_area_protegida_otra_infraestructuras_path(@area_protegida), :remote => true, :class => "cancel_button" %>
<% when "Especies introducidas" %>
  <%= link_to 'Cancelar', admin_area_protegida_especie_introducidas_path(@area_protegida), :remote => true, :class => "cancel_button" %>
<% when "Actividades Hidrocarburíferas" %>
  <%= link_to 'Cancelar', admin_area_protegida_actividad_hidrocarburiferas_path(@area_protegida), :remote => true, :class => "cancel_button" %>
<% when "Invasiones" %>
  <%= link_to 'Cancelar', admin_area_protegida_invasions_path(@area_protegida), :remote => true, :class => "cancel_button" %>
<% else %>
  <%= link_to 'Cancelar', admin_area_protegida_amenazas_path, :remote => true, :class => "cancel_button" %>
<% end %>

app/views/admin/amenazas/edit.html.erb
<!-- Deprecated -->
<!-- <h1>Editar Amenaza</h1>

<%= render 'form' %>
 -->

app/views/admin/amenazas/index.html.erb
<h2><%= @area_protegida.AREA_NOMBRE %></h2>
<h3>Amenazas</h3>
<table>
  <tr>
    <th>Amenaza fecha levantada</th>
    <th>Amenaza fecha evento</th>
    <th>Amenaza contraventor tipo</th>
    <th>Amenaza tipo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @amenazas.each do |amenaza| %>
  <tr>
    <td><%= amenaza.AMENAZA_FECHA_LEVANTADA %></td>
    <td><%= amenaza.AMENAZA_FECHA_EVENTO %></td>
    <td><%= amenaza.AMENAZA_CONTRAVENTOR_TIPO %></td>
    <td><%= amenaza.AMENAZA_TIPO %></td>
    <td><%= link_to 'Editar', edit_admin_area_protegida_amenaza_path(@area_protegida, amenaza)  %></td>
    <td><%= link_to 'Eliminar', admin_area_protegida_amenaza_path(@area_protegida, amenaza), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Añadir amenaza', new_admin_area_protegida_amenaza_path %>

app/views/admin/amenazas/new.html.erb
<h1><%= @amenaza.new_record? ? "Añadir" : "Editar" %> Amenaza</h1>

<%= render 'admin/amenazas/form' %>

app/views/admin/amenazas/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Area id:</b>
  <%= @amenaza.AREA_ID %>
</p>

<p>
  <b>Amenaza fecha levantada:</b>
  <%= @amenaza.AMENAZA_FECHA_LEVANTADA %>
</p>

<p>
  <b>Amenaza fecha evento:</b>
  <%= @amenaza.AMENAZA_FECHA_EVENTO %>
</p>

<p>
  <b>Amenaza contraventor tipo:</b>
  <%= @amenaza.AMENAZA_CONTRAVENTOR_TIPO %>
</p>

<p>
  <b>Amenaza tipo:</b>
  <%= @amenaza.AMENAZA_TIPO %>
</p>


<%= link_to 'Editar', edit_admin_area_protegida_amenaza_path(@area_protegida, @amenaza)  %> 
<%= link_to 'Atrás', admin_area_protegida_informacion_administrativas_path  %>