config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Sigtap::Application.routes.draw do

  namespace :admin do
    resources :area_protegidas, path: "areas_protegidas" do

      member do
        get :downloadable
      end

      resources :informacion_legals, path: "informacion_legal"
      resources :informacion_administrativas, path: "informacion_administrativa"
      resources :informacion_geograficas, path: "informacion_geografica"
      resources :categorizacions, path: "categorizaciones"
      resources :informacion_climaticas, path: "informacion_climatica"
      resources :informacion_turisticas, path: "informacion_turistica"
      resources :amenazas, path: "amenaza"
      resources :biodiversidads, path: "biodiversidad" do
        resources :biodiversidad_especies
      end
      resources :informacion_hidrograficas, path: "informaciones_hidrograficas"
      resources :deforestacions, path: "deforestaciones"
      resources :extraccion_ilegals, path: "extracciones_ilegales"
      resources :amenaza_especies
      resources :incendios
      resources :actividad_agropecuaria, path: "actividad_agropecuaria"
      resources :mineria_ilegals, path: "mineria_ilegal"
      resources :mineria_legals, path: "mineria_legales"
      resources :infraestructura_vials, path: "infraestructuras_viales"
      resources :otra_infraestructuras, path: "otras_infraestructuras"
      resources :especie_introducidas, path: "especies_introducidas"
      resources :comunidads, path: "comunidades"
      resources :actividad_hidrocarburiferas, path: "actividades_hidrocarburiferas"
      resources :conflicto_socioambientals, path: "conflictos_socioambientales"
      resources :invasions, path: "invasiones"
      resources :sitio_turisticos, path: "sitios_turisticos"
    end
  end

  resources :areas_protegidas do
    collection do
      get :maps
      get 'show/:id' => 'areas_protegidas#show'
    end
  end
  resources :sessions, path: :login
  get 'login' => 'sessions#index', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  root :to => 'areas_protegidas#maps'

  mount Sidekiq::Web, at: '/sidekiq_web', :constraints => AdminConstraint.new

  match '*a', :to => 'application#routing_error'
end

app/models/otra_infraestructura.rb
class OtraInfraestructura < ActiveRecord::Base
  attr_accessible :AMENAZA_ID,
                  :OTR_INF_AREA_COBERTURA,
                  :OTR_INF_TIPO,
                  :tipo

  self.table_name = "OTRAS_INFRAESTRUCTURAS"
  self.primary_key = "OTR_INF_ID"

  belongs_to :amenaza, foreign_key: :AMENAZA_ID

  # validate :at_least_one_tipo
  # validates :OTR_INF_AREA_COBERTURA, :presence => true
  validates :OTR_INF_AREA_COBERTURA, :numericality => {:greater_than => 0}, :allow_blank => true

  # def OTR_INF_TIPO=( array )
  #   if array.include? ""
  #     array.delete ""
  #   end
  #   write_attribute :OTR_INF_TIPO, array.to_json
  # end
def tipo=( array )
    array.delete("") if array.include?("")
    write_attribute(:OTR_INF_TIPO, array.join(","))
  end
  def OTR_INF_TIPO
    read_attribute(:OTR_INF_TIPO).to_s.split(",")
  end

  alias_method :tipo, :OTR_INF_TIPO

  # def at_least_one_tipo
  #   errors.add(:tipo, "Se debe escoger al menos un tipo") if tipo.length == 0
  # end

end

app/controllers/admin/otra_infraestructuras_controller.rb
# encoding: utf-8
class Admin::OtraInfraestructurasController < AdminController
  before_filter :find_area_protegida, :set_div_for_js
  # GET /otra_infraestructuras
  # GET /otra_infraestructuras.json
  def index
    # @otra_infraestructuras = OtraInfraestructura.all
    @amenazas = @area_protegida.amenazas_otras_infraestructuras.all
  end

  # GET /otra_infraestructuras/1
  # GET /otra_infraestructuras/1.json
  def show
    redirect_to action: :index
    # @otra_infraestructura = OtraInfraestructura.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @otra_infraestructura }
    # end
  end

  # GET /otra_infraestructuras/new
  # GET /otra_infraestructuras/new.json
  def new
    # @otra_infraestructura = OtraInfraestructura.new

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @otra_infraestructura }
    # end
    @amenaza = @area_protegida.amenazas.new(:AMENAZA_TIPO => "Obras de infraestructura")
    @amenaza.otras_infraestructuras.build

    render 'admin/amenazas/new'
  end

  # GET /otra_infraestructuras/1/edit
  def edit
    # @otra_infraestructura = OtraInfraestructura.find(params[:id])
    @amenaza = @area_protegida.amenazas.find params[:id]
    render 'admin/amenazas/new'
  end

  # POST /otra_infraestructuras
  # POST /otra_infraestructuras.json
  def create
    redirect_to action: :index
    # @otra_infraestructura = OtraInfraestructura.new(params[:otra_infraestructura])

    # respond_to do |format|
    #   if @otra_infraestructura.save
    #     format.html { redirect_to @otra_infraestructura, notice: 'Otra infraestructura was successfully created.' }
    #     format.json { render json: @otra_infraestructura, status: :created, location: @otra_infraestructura }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @otra_infraestructura.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /otra_infraestructuras/1
  # PUT /otra_infraestructuras/1.json
  def update
    redirect_to action: :index
    # @otra_infraestructura = OtraInfraestructura.find(params[:id])

    # respond_to do |format|
    #   if @otra_infraestructura.update_attributes(params[:otra_infraestructura])
    #     format.html { redirect_to @otra_infraestructura, notice: 'Otra infraestructura was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: "edit" }
    #     format.json { render json: @otra_infraestructura.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /otra_infraestructuras/1
  # DELETE /otra_infraestructuras/1.json
  def destroy
    @otra_infraestructura = OtraInfraestructura.find(params[:id])
    @otra_infraestructura.destroy

    respond_to do |format|
      format.html { redirect_to admin_area_protegida_otra_infraestructuras_path(@area_protegida)   }
      format.json { head :no_content }
      format.js {
        index
        render :index
      }
    end
  end

  private

    def set_div_for_js
      @div_name = "#obras_de_infraestructura"
    end
end

app/helpers/otra_infraestructuras_helper.rb
module OtraInfraestructurasHelper
end

app/views/admin/otra_infraestructuras/_form.html.erb
  <div class="field">
    <%= f.label :OTR_INF_AREA_COBERTURA, "Área de cobertura de obras" %>
    <%= f.number_field :OTR_INF_AREA_COBERTURA, :placeholder => "(en hectáreas)", :step => "any" %>
    <span class="help-inline">
        Por favor verifica que hayas ingresado un número y que sea mayor a 0.
      </span> 

  </div>

<!-- <div class="field">
    <%= f.label :OTR_INF_TIPO, "Tipos de Infraestructura (presione SHIFT o CTRL para seleccionar varias)" %>
    <%= f.select :OTR_INF_TIPO, ["Represas", "Plantas generadoras de energía", "Telecomunicaciones", "Edificaciones no planificadas"], {}, {:multiple => true} %>
      </div> -->


      <div class="info_title">Tipos de Infraestructura</div>
  <div class="info_content">
    <div class="field">
      <div><small>(Presione SHIFT o CTRL para marcar varias)</small></div>
      <%
        tipo = [
          "Represas",
          "Plantas generadoras de energía",
          "Telecomunicaciones",
          "Edificaciones no planificadas"
        ]
      %>
      <%= f.select :tipo, tipo, {}, {:multiple => true} %>
      <span class="help-inline">Se debe escoger al menos un tipo</span>
    </div>
  </div>


   <div><%= f.link_to_remove "Obras de infraestructura", :class => "delete_destroy" %></div> 

app/views/admin/otra_infraestructuras/_index.html.erb
<% amenazas.each do |amenaza| %>
  <div class="has_container has_margin">
	  <%= render 'admin/amenazas/amenaza', amenaza: amenaza%>
  		<div></div>
  		<% amenaza.otras_infraestructuras.each do |otra_infraestructura| %>
    		<div class="info_content">
      		<%= render 'admin/otra_infraestructuras/otra_infraestructura', otra_infraestructura: otra_infraestructura%>
    		</div>
  		<% end %>
  </div>
<% end %>

<% if current_user and current_user.is_admin? %>
  <div class="">
    <%= link_to 'Añadir obras de infraestructura', new_admin_area_protegida_otra_infraestructura_path(@area_protegida), :class => "crear_nuevo", :remote => true %> 
  </div>
<% end %>

app/views/admin/otra_infraestructuras/_otra_infraestructura.html.erb
<div class="info_title">
  Obras de infraestructura
</div>
<div class="info_content">

  <% unless otra_infraestructura.OTR_INF_AREA_COBERTURA.blank? %>
    <div>
      <strong>Área de cobertura de obras:</strong>
      <%= otra_infraestructura.OTR_INF_AREA_COBERTURA %> ha
    </div>
  <% end %>

  <% unless otra_infraestructura.OTR_INF_TIPO.length == 0 %>
  <div class="info_title">Tipos de infraestructura</div>
  <div class="info_content">
    <% otra_infraestructura.OTR_INF_TIPO.each do |tipo| %>
      <div><%= tipo %></div>
    <% end %>
  </div>
<% end %>


</div>

<% if current_user and current_user.is_admin? %>
  <div>
    <%= link_to 'Editar', edit_admin_area_protegida_otra_infraestructura_path(@area_protegida, otra_infraestructura.amenaza), :class => "editar_edit", :remote => true %>
    <%= link_to 'Eliminar', admin_area_protegida_otra_infraestructura_path(@area_protegida, otra_infraestructura), method: :delete, data: { confirm: '¿Estás seguro? Esta acción es irreversible' }, :class => "delete_destroy", :remote => true %>
  </div>
<% end %>

app/views/admin/otra_infraestructuras/index.html.erb
<h2><%= @area_protegida.AREA_NOMBRE %></h2>
<h3>Otra infraestructura</h3>

<%= render 'index', amenazas: @amenazas, show_links: true %>

<br>
<%= link_to "Atrás", admin_area_protegida_path(@area_protegida), :class => "atras_back" %>
<%= link_to 'Añadir Amenaza: Otra infraestructura', new_admin_area_protegida_otra_infraestructura_path(@area_protegida), :class => "crear_nuevo" %>

app/views/admin/otra_infraestructuras/index.js.erb
<%= js_content "#obras_de_infraestructura", j(render('index', amenazas: @amenazas)) %>

app/views/admin/otra_infraestructuras/show.html.erb
<%= render 'otra_infraestructura', otra_infraestructura: @otra_infraestructura %>