config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Sigtap::Application.routes.draw do

  namespace :admin do
    resources :area_protegidas, path: "areas_protegidas" do

      member do
        get :downloadable
      end

      resources :informacion_legals, path: "informacion_legal"
      resources :informacion_administrativas, path: "informacion_administrativa"
      resources :informacion_geograficas, path: "informacion_geografica"
      resources :categorizacions, path: "categorizaciones"
      resources :informacion_climaticas, path: "informacion_climatica"
      resources :informacion_turisticas, path: "informacion_turistica"
      resources :amenazas, path: "amenaza"
      resources :biodiversidads, path: "biodiversidad" do
        resources :biodiversidad_especies
      end
      resources :informacion_hidrograficas, path: "informaciones_hidrograficas"
      resources :deforestacions, path: "deforestaciones"
      resources :extraccion_ilegals, path: "extracciones_ilegales"
      resources :amenaza_especies
      resources :incendios
      resources :actividad_agropecuaria, path: "actividad_agropecuaria"
      resources :mineria_ilegals, path: "mineria_ilegal"
      resources :mineria_legals, path: "mineria_legales"
      resources :infraestructura_vials, path: "infraestructuras_viales"
      resources :otra_infraestructuras, path: "otras_infraestructuras"
      resources :especie_introducidas, path: "especies_introducidas"
      resources :comunidads, path: "comunidades"
      resources :actividad_hidrocarburiferas, path: "actividades_hidrocarburiferas"
      resources :conflicto_socioambientals, path: "conflictos_socioambientales"
      resources :invasions, path: "invasiones"
      resources :sitio_turisticos, path: "sitios_turisticos"
    end
  end

  resources :areas_protegidas do
    collection do
      get :maps
      get 'show/:id' => 'areas_protegidas#show'
    end
  end
  resources :sessions, path: :login
  get 'login' => 'sessions#index', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  root :to => 'areas_protegidas#maps'

  mount Sidekiq::Web, at: '/sidekiq_web', :constraints => AdminConstraint.new

  match '*a', :to => 'application#routing_error'
end

app/models/informacion_hidrografica.rb
class InformacionHidrografica < ActiveRecord::Base
  attr_accessible :AREA_ID,
                  :HIDRO_CUENCAS_PRESENTES,
                  :HIDRO_HUMEDALES,
                  :HIDRO_RIOS_PRINCIPALES,
                  :hidro_humedales_json

  attr_accessor :hidro_humedales_json


  self.table_name = "INFORMACION_HIDROGRAFICA"
  self.primary_key = "HIDRO_ID"

  validates :HIDRO_CUENCAS_PRESENTES, :presence => true
  validates :HIDRO_RIOS_PRINCIPALES, :presence => true

  belongs_to :area_protegida, foreign_key: :AREA_ID

  def HIDRO_HUMEDALES
    @humedales = self.read_attribute(:HIDRO_HUMEDALES)
    if @humedales.blank?
      []
    else
      JSON.parse @humedales
    end
  end

  def hidro_humedales_json=( humedales_str )
    self.HIDRO_HUMEDALES = humedales_str.split(",").to_json
  end

end

app/controllers/admin/informacion_hidrograficas_controller.rb
# encoding: utf-8
class Admin::InformacionHidrograficasController < AdminController
  before_filter :find_area_protegida
  # GET /informacion_turisticas
  # GET /informacion_turisticas.json
  def index
    @informacion_hidrograficas = @area_protegida.informaciones_hidrograficas.all
  end

  # GET /informacion_hidrograficas/1
  # GET /informacion_hidrograficas/1.json
  def show
    redirect_to action: :index
    # @informacion_hidrografica = @area_protegida.informaciones_hidrograficas.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @informacion_hidrografica }
    # end
  end

  # GET /informacion_hidrograficas/new
  # GET /informacion_hidrograficas/new.json
  def new
    @informacion_hidrografica = @area_protegida.informaciones_hidrograficas.build
    render :edit
  end

  # GET /informacion_hidrograficas/1/edit
  def edit
    @informacion_hidrografica = @area_protegida.informaciones_hidrograficas.find(params[:id])
  end

  # POST /informacion_hidrograficas
  # POST /informacion_hidrograficas.json
  def create
    @informacion_hidrografica = @area_protegida.informaciones_hidrograficas.new(params[:informacion_hidrografica])

    respond_to do |format|
      if @informacion_hidrografica.save
        format.html { redirect_to admin_area_protegida_informacion_hidrografica_path(@area_protegida, @informacion_hidrografica), notice: 'Información hidrográfica creada'} 
        format.json { render json: @informacion_hidrografica, status: :created, location: @informacion_hidrografica }
        format.js {
          index
          render :index
        }
      else
        format.html { render action: "new" }
        format.json { render json: @informacion_hidrografica.errors, status: :unprocessable_entity }
        format.js {
          render :edit
        }
      end
    end
  end

  # PUT /informacion_hidrograficas/1
  # PUT /informacion_hidrograficas/1.json
  def update
    @informacion_hidrografica = @area_protegida.informaciones_hidrograficas.find(params[:id])

    respond_to do |format|
      if @informacion_hidrografica.update_attributes(params[:informacion_hidrografica])
        format.html { redirect_to admin_area_protegida_informacion_hidrograficas_path(@area_protegida), notice: 'Informacion hidrográfica actualizada.' }
        format.json { head :no_content }
        format.js {
          index
          render :index
        }
      else
        format.html { render action: "edit" }
        format.json { render json: @informacion_hidrografica.errors, status: :unprocessable_entity }
        format.js {
          render :edit
        }
      end
    end
  end

  # DELETE /informacion_hidrograficas/1
  # DELETE /informacion_hidrograficas/1.json
  def destroy
    @informacion_hidrografica = @area_protegida.informaciones_hidrograficas.find(params[:id])
    @informacion_hidrografica.destroy

    respond_to do |format|
      format.html { redirect_to admin_area_protegida_informacion_hidrograficas_path(@area_protegida) }
      format.json { head :no_content }
      format.js {
        index
        render :index
      }
    end
  end
end

app/helpers/informacion_hidrograficas_helper.rb
# encoding: utf-8
module InformacionHidrograficasHelper

  def humedales_form_table( selected=[], opciones=humedales_form_table_opciones )
    cb_class = "informacion_hidrografica_form_humedales_checkbox"
    html = ""
    opciones.each do |key, value|
      html += "<tr>"
      html += "<td><b>#{key}:</b></td>"
      html += "<td>"
      value.each do |v|
        html += "<div>"
        html += "<input type='checkbox' class='#{cb_class}'"
        if selected.include? v
          html += "checked='checked'"
        end
        html += "> "
        html += "<span>"
        html += "#{v}"
        html += "</span>"
        html += "</div>"
      end
      html += "</td>"
      html += "</tr>"
    end
    raw html
  end

  def humedales_form_table_opciones
    {
      "Marinos" => [
        "Costeros",
        "Costas Rocosas",
        "Arrecifes de Coral"
      ],
      "Estuarios" => [
        "Deltas",
        "Marismas de Marea",
        "Manglares"
      ],
      "Lacustres" => [
        "Lagos",
        "Lagunas"
      ],
      "Ribereños" => [
        "Ríos",
        "Arroyos"
      ],
      "Palustres" => [
        "Marismas",
        "Pantanos",
        "Ciénegas",
        "Turberas"
      ]
    }
  end

end

app/views/admin/informacion_hidrograficas/_form.html.erb
  <%= form_for([:admin, @area_protegida, @informacion_hidrografica], html: { id: "form_for_informacion_hidrografica"}, :remote => true) do |f| %>

  <div class="field">
    <%= f.label :AREA_ID, "Área protegida" %>
    <input type="text" disabled="disabled" value="<%= @area_protegida.AREA_NOMBRE %>">
    <%= f.hidden_field :AREA_ID %>
  </div>

  <div class="field">
    <%= f.label :HIDRO_CUENCAS_PRESENTES, "Cuencas hidrográficas presentes" %>
    <%= f.text_field :HIDRO_CUENCAS_PRESENTES, :required => true %>
    <%= form_helper_not_blank %>
  </div>

  <div class="field">
    <%= f.label :HIDRO_RIOS_PRINCIPALES, "Ríos principales" %>
    <%= f.text_field :HIDRO_RIOS_PRINCIPALES, :required => true %>
    <%= form_helper_not_blank %>
  </div>

  <div class="field">
    <%= f.label :HIDRO_HUMEDALES, "Humedales" %>
    <%= render 'humedales_form', f: f %>
    <%= f.hidden_field :hidro_humedales_json %>
  </div>
  
  <div class="actions">
    <%= f.submit "#{f.object.new_record? ? "Crear" : "Actualizar"} Información Hidrográfica", :disable_with => "Enviando.." %>
  </div>
<% end %>

<%= link_to "Cancelar", admin_area_protegida_informacion_hidrograficas_path(@area_protegida), :class => "cancel_button", :remote => true %>

<%= javascript_tag do %>
  $( function () {
    window.InformacionHidrograficaForm.init();
  });
<% end %>

app/views/admin/informacion_hidrograficas/_humedales.html.erb
<%marinos = []%>
<%estuarios = []%>
<%lacustres = []%>
<%ribareños = []%>
<%palustres = []%>
<% humedales.each do |humedal| %>
      <% case humedal %>
        <% when "Costeros", "Costas Rocosas", "Arrecifes de Coral" %>
          <%marinos.push(humedal)%>
        <% when "Deltas", "Marismas de Marea", "Manglares" %>
          <%estuarios.push(humedal)%>
        <% when "Lagos", "Lagunas" %>
          <%lacustres.push(humedal)%>
        <% when "Ríos", "Arroyos" %>
          <%ribareños.push(humedal)%>
          <% when "Marismas", "Pantanos", "Ciénegas", "Turberas" %>
          <%palustres.push(humedal)%>        
      <% end %>
<% end %>
<%unless marinos.empty?%>
  <div class="info_title">
      Marinos:
  </div>
  <div class="info_content">
    <% marinos.each do |marino| %>
    <%= marino %> <br>
  <% end %>
  </div>
  <%end%>

<%unless estuarios.empty?%>
  <div class="info_title">
      Estuarios:
  </div>
  <div class="info_content">
    <% estuarios.each do |estuario| %>
    <%= estuario %> <br>
  <% end %>
  </div>
<%end%>

<%unless lacustres.empty?%>
  <div class="info_title">
      Lacustres:
  </div>
  <div class="info_content">
    <% lacustres.each do |lacustre| %>
    <%= lacustre %> <br>
  <% end %>
  </div>
  <%end%>

<%unless ribareños.empty?%>
  <div class="info_title">
      Ribareños:
  </div>
  <div class="info_content">
    <% ribareños.each do |ribareño| %>
    <%= ribareño %> <br>
  <% end %>
  </div>
  <%end%>

<%unless palustres.empty?%>
  <div class="info_title">
      Palustres:
  </div>
  <div class="info_content">
    <% palustres.each do |palustre| %>
    <%= palustre %> <br>
  <% end %>
  </div>
  <%end%>

app/views/admin/informacion_hidrograficas/_humedales_form.html.erb
<table class="informacion_hidrografica_humedales_form_table no_left">
  <tbody>
    <%= humedales_form_table f.object.HIDRO_HUMEDALES %>
  </tbody>
</table>

app/views/admin/informacion_hidrograficas/_index.html.erb
<% informaciones_hidrograficas.each do |informacion_hidrografica| %>
  <%= render 'admin/informacion_hidrograficas/informacion_hidrografica', informacion_hidrografica: informacion_hidrografica %>
<% end %>

<% if current_user and current_user.is_admin? %>
  <div>
    <%= link_to 'Añadir información hidrográfica', new_admin_area_protegida_informacion_hidrografica_path(@area_protegida), :class => "crear_nuevo", :remote => true %>
  </div>
<% end %>

app/views/admin/informacion_hidrograficas/_informacion_hidrografica.html.erb
<div class="has_container">
    <div class="info_title">
      Cuencas Presentes:
    </div>
    <div class="info_content">
      <% informacion_hidrografica.HIDRO_CUENCAS_PRESENTES.split(";").each do |cuenca| %>
        <%=cuenca%></br>
      <%end%>
    </div>
    <div class="info_title">
      Ríos principales:
    </div>
    <div class="info_content">
      <% informacion_hidrografica.HIDRO_RIOS_PRINCIPALES.split(";").each do |rios| %>
        <%=rios%></br>
      <%end%>
    </div>
    
    <% unless informacion_hidrografica.HIDRO_HUMEDALES.count == 0 %>
      <div class="info_title">
        Humedales:
      </div>
      <div class="info_content">
        <%= render 'admin/informacion_hidrograficas/humedales', humedales: informacion_hidrografica.HIDRO_HUMEDALES %>
      </div>
    <% end %>

  <% if current_user and current_user.is_admin? %>
    <div>
      <%= link_to 'Editar', edit_admin_area_protegida_informacion_hidrografica_path(@area_protegida, informacion_hidrografica), :class => "editar_edit", :remote => true %>
      <%= link_to 'Eliminar', admin_area_protegida_informacion_hidrografica_path(@area_protegida, informacion_hidrografica), method: :delete, data: { confirm: '¿Estás seguro? Esta acción es irreversible' }, :class => "delete_destroy", :remote => true %>
    </div>
  <% end %>
  
</div>

app/views/admin/informacion_hidrograficas/edit.html.erb
<h1>Editando Información Hidrográfica</h1>

<%= render 'form' %>

app/views/admin/informacion_hidrograficas/edit.js.erb
<%= js_content "#información_hidrográfica", j(render('form')) %>

app/views/admin/informacion_hidrograficas/index.html.erb
<%= javascript_tag do %>
  window.location = '/admin/areas_protegidas';
<% end -%>

<h2><%= @area_protegida.AREA_NOMBRE %></h2>
<h3>Información Hidrográfica</h3>

<%= render 'informaciones_hidrograficas', informacion_hidrograficas: @informacion_hidrograficas, area_protegida: @area_protegida %>

<br />

<%= link_to "Atrás", admin_area_protegida_path(@area_protegida), :class => "atras_back" %>
<%= link_to 'Añadir información hidrográfica', new_admin_area_protegida_informacion_hidrografica_path, :class => "crear_nuevo"  %>

app/views/admin/informacion_hidrograficas/index.js.erb
<%= js_content "#información_hidrográfica", j(render('index', informaciones_hidrograficas: @informacion_hidrograficas)) %>

app/views/admin/informacion_hidrograficas/new.html.erb
<h1>Nueva información Hidrográfica</h1>

<%= render 'form' %>

app/views/admin/informacion_hidrograficas/new.js.erb
<%= js_content "#información_hidrográfica", j(render('form')) %>

app/views/admin/informacion_hidrograficas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Area id:</b>
  <%= @informacion_hidrografica.AREA_ID %>
</p>

<p>
  <b>Hidro cuencas presentes:</b>
  <%= @informacion_hidrografica.HIDRO_CUENCAS_PRESENTES %>
</p>

<p>
  <b>Hidro rios principales:</b>
  <%= @informacion_hidrografica.HIDRO_RIOS_PRINCIPALES %>
</p>

<p>
  <b>Hidro humedales:</b>
  <%= @informacion_hidrografica.HIDRO_HUMEDALES %>
</p>


<%= link_to 'Edit', edit_informacion_hidrografica_path(@informacion_hidrografica) %> |
<%= link_to 'Back', informacion_hidrograficas_path %>